package cxf.org.camunda.webservice.ame;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2017-07-10T17:04:36.162+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "RicevutaRichiestaAcquirenteService", 
                  wsdlLocation = "file:/C:/Users/afaie/workspace/soseng/src/main/resources/RicevutaRichiestaAcquirenteService.wsdl",
                  targetNamespace = "http://ame.webservice.camunda.org/") 
public class RicevutaRichiestaAcquirenteService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ame.webservice.camunda.org/", "RicevutaRichiestaAcquirenteService");
    public final static QName RicevutaRichiestaAcquirentePort = new QName("http://ame.webservice.camunda.org/", "RicevutaRichiestaAcquirentePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/afaie/workspace/soseng/src/main/resources/RicevutaRichiestaAcquirenteService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RicevutaRichiestaAcquirenteService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/afaie/workspace/soseng/src/main/resources/RicevutaRichiestaAcquirenteService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RicevutaRichiestaAcquirenteService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RicevutaRichiestaAcquirenteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RicevutaRichiestaAcquirenteService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RicevutaRichiestaAcquirenteService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RicevutaRichiestaAcquirenteService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RicevutaRichiestaAcquirenteService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RicevutaRichiestaAcquirente
     */
    @WebEndpoint(name = "RicevutaRichiestaAcquirentePort")
    public RicevutaRichiestaAcquirente getRicevutaRichiestaAcquirentePort() {
        return super.getPort(RicevutaRichiestaAcquirentePort, RicevutaRichiestaAcquirente.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RicevutaRichiestaAcquirente
     */
    @WebEndpoint(name = "RicevutaRichiestaAcquirentePort")
    public RicevutaRichiestaAcquirente getRicevutaRichiestaAcquirentePort(WebServiceFeature... features) {
        return super.getPort(RicevutaRichiestaAcquirentePort, RicevutaRichiestaAcquirente.class, features);
    }

}
