
package cxf.org.camunda.webservice.ame;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2017-07-10T17:04:36.324+02:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "SOAPException", targetNamespace = "http://ame.webservice.camunda.org/")
public class SOAPException_Exception extends Exception {
    
    private cxf.org.camunda.webservice.ame.SOAPException soapException;

    public SOAPException_Exception() {
        super();
    }
    
    public SOAPException_Exception(String message) {
        super(message);
    }
    
    public SOAPException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SOAPException_Exception(String message, cxf.org.camunda.webservice.ame.SOAPException soapException) {
        super(message);
        this.soapException = soapException;
    }

    public SOAPException_Exception(String message, cxf.org.camunda.webservice.ame.SOAPException soapException, Throwable cause) {
        super(message, cause);
        this.soapException = soapException;
    }

    public cxf.org.camunda.webservice.ame.SOAPException getFaultInfo() {
        return this.soapException;
    }
}
